### PR TITLE
Story 22 with additional fixes

### LINKED ISSUE #115: Story 22 Feature Test Admin Order Show
As an authenticated Admin, when I visit an individual order page Then I can see the order’s date and time. And I can see the purchaser’s full name and address. And I can see, for each item on the order:

The item’s name, which is linked to the item page.
Quantity in this order.
Price
Line item subtotal. And I can see the total for the order. And I can see the status for the order.

### PR DESCRIPTION
**Pull request by dionew1**
### Description
Fixed functions and created admin conditional on order show
Styled Order Show

## Proposed Changes
-Styled order show page
-Clears Cart after order is placed
-Added link to Orders index in nav bar
-Corrected error in order calculation for show
-Add conditional for order information on show page for admin
-All tests passing

### CODE REVIEW

File: app/models/order.rb [hunk 1]
```diff
@@ -11,6 +11,17 @@ def format_date(date)
     date.strftime('%m/%d/%Y')
   end
 
+  def create_order_items(cart)
+    items = Item.find(cart.keys.map { |key| key.to_i })
+    items.each do |item|
```
Comment (hmorri32) [inline app/models/order.rb:16]: nice abstraction here
